//
//  DogData.swift
//  History_of_the_dog_breeds
//
//  Created by Dat, Tran Xuan Hoang on 04/08/2023.
//

import Foundation
import CoreLocation

var dogs:[Dog] = [
    Dog(title: "The Shiba Inu (柴犬, Japanese: [ɕiba inɯ])", headline: "The Shiba Inu (柴犬, Japanese: [ɕiba inɯ]) is a breed of hunting dog from Japan. A small-to-medium breed, it is the smallest of the six original and distinct spitz breeds of dog native to Japan.[1] Its name literally translates to brushwood dog, as it is used to flush game.A small, alert, and agile dog that copes very well with mountainous terrain and hiking trails, the Shiba Inu was originally bred for hunting. It looks similar to other Japanese dog breeds such as the Akita Inu or Hokkaido, but the Shiba Inu is a different breed with a distinct bloodline, temperament, and smaller size than other Japanese dog breeds.", dogEra: "19th century", summary: ["19th century","mountainous areas of the Chūbu region","43"],
        description:"""
             The Shiba Inu has been identified as a basal breed that predates the emergence of the modern breeds in the 19th century. Dogs with a similar appearance to the Shiba Inu were represented in dogū made during the prehistoric Jōmon period of Japanese history.
             
             The Shiba Inu was bred to hunt and flush small game, such as birds and rabbits. Shiba lived in the mountainous areas of the Chūbu region. During the Meiji Restoration, western dog breeds were imported and crosses between these and native Japanese breeds became popular. From 1912 to 1926, almost no pure Shiba remained. From around 1928, hunters and intellectuals began to show interest in the protection of the remaining pure Shiba.
             
             Despite efforts to preserve the breed, the Shiba nearly became extinct during World War II due to a combination of food shortage and a post-war distemper epidemic. All subsequent dogs were bred from the only three surviving bloodlines. These bloodlines were the Shinshu Shiba from Nagano Prefecture, the Mino Shiba from the former Mino Province in the south of present-day Gifu Prefecture, and the San'in Shiba from Tottori and Shimane Prefectures.
             
             The Shinshu Shibas possessed a solid undercoat, with a dense layer of guard-hairs, and were small and red in color. The Mino Shibas tended to have thick, prick ears, and possessed a sickle tail, rather than the common curled tail found on most modern Shibas. The San'in Shibas were larger than most modern shibas, and tended to be black, without the common tan and white accents found on modern black-and-tan shibas.
             
             When the study of Japanese dogs was formalized in the early and mid-20th century, these three strains were combined into one overall breed, the Shiba Inu. The first Japanese breed standard for the Shiba, the Nippo Standard, was published in 1934. In December 1936, the Shiba Inu was recognized as a Natural Monument of Japan through the Cultural Properties Act, largely due to the efforts of Nippo (Nihon Ken Hozonkai), the Association for the Preservation of the Japanese Dog.
             
             In 1954, an armed service family brought the first Shiba Inu to the United States. In 1979, the first recorded litter was born in the United States. The Shiba was recognized by the American Kennel Club in 1992 and added to the AKC Non-Sporting Group in 1993. It is now primarily kept as a pet both in Japan and abroad. According to the American Kennel Club, the Shiba Inu is the number one companion dog in Japan. In the United States, the growing popularity of the Shiba Inu is evident as the American Kennel Club Registration Statistics ranked the breed in 44th place in 2016, a rise from 50th place in 2012.


             """,
        fact: "In 2004, an earthquake struck the village of Yamakoshi in Japan. When her family’s home collapsed, a Shiba Inu named Mari sprang into action to save her puppies and her elderly owner. She moved her puppies to a safe place and then found and woke up her owner, who had been trapped underneath a fallen cabinet. He managed to free himself and was eventually evacuated from the area by helicopter. He was forced to leave Mari and her pups behind, but when he returned two weeks later he found that they were all alive. Mari’s story was made into a Japanese movie called A Tale of Mari and Her Three Puppies.", imageName:"shiba",locationCoordinate: CLLocationCoordinate2D(latitude: 35.183334, longitude: 136.899994) ),
    
        Dog(title: "The Akita (秋田, Akita, Japanese pronunciation: [akʲita])", headline: "The Akita (秋田, Akita, Japanese pronunciation: [akʲita]) is a Japanese dog breed of large size. Originating from the mountains of northern Japan, the Akita has a short double coat similar to that of many other northern spitz breeds. Historically, they were used by samurai for guarding, fighting and the hunting of bears.The Akita is a powerful, independent, and dominant breed, commonly aloof with strangers, but affectionate and deeply loyal with its family. As a breed, Akitas are generally hardy. The two separate varieties of Akita are a pure Japanese strain, called Akita Inu or Akita-ken, and a larger mixed strain, commonly referred to as the American Akita. However, it is subject to debate as to whether the Akita strains are distinct, or if they constitute one, single breed." , dogEra: "16th century", summary: ["16th century","Odate, Akita","55"],
            description:"""
                 The Akita Inu originated in the snowy and rural lands of Odate, Akita Prefecture, a wild and mountainous region of Japan. They were trained to hunt animals such as elk, wild boar, and Ussuri brown bears. This breed in the 1600s was involved in dog fighting, which at the time was popular in Japan. From the 1500s into the 1800s, the Akita served as companions for samurai.

                 In 1931, the Akita was officially declared a Japanese natural monument. The mayor of Odate City in Akita Prefecture organized the Akita Inu Hozonkai to preserve the original Akita as a Japanese natural treasure through careful breeding.

                 In 1933, Heishiro Takaku (Takahisa), one of the early members of Nippo in Tokyo and later of the Nipponinu Kyokai (Nikkyo) in Osaka and Katsuichi (Shoichi) each published articles on a proposed Japanese dog standard, which Included the Akita dog. Akita dogs revealed the most non-uniformity at that time, when compared to medium and small Japanese dogs, due to being outcrossed to the Tosa fighting dog, and other Imported foreign dogs. Then in 1934, the first Japanese breed standard for the Akita Inu was listed, following the breed's declaration as a natural monument of Japan.

                 The Akita breed was used during the Russo-Japanese War to track prisoners of war and lost sailors.During World War II, the Akita was considered a non-military breed and was crossed with German Shepherds in an attempt to save them from the wartime government order for all non-military dogs to be culled. Some were used as scouts and guards during the war.

                 A native Japanese breed known as Matagi (hunting dog) was used along with the Hokkaido Inu breed to mix back into the remaining Akita dogs to restore the breed. There were many lines of Akita, but the most influential were the Dewa and Ichinoseki.  Both lines contributed to the foundation stock for both Akita types, and many exported dogs were a combination of these lines. According to one Japanese judge, the greatest difference between Japanese- and American-bred Akitas is that the latter still show much evidence of the Dewa strain. In the early 1900's, Dewa-line akitas were heavily favored and did well in show. Kongo-go (from the Heirakudo Kennel of Eikichi Hiraizumi) is considered to be the most influential dog of that line. For a time, it was said: “Kongokei ni arazunba Akitainu ni arazu" (If not from the Kongo line, ‘tis not an Akita dog.)

                 However, the Dewa-line later went into a decline because Japanese breeders felt that the akita did not give the impression of a Japanese dog, so began to breed towards an ideal type reminiscent of other Nihon-ken. The Dewa line was stereotyped as the “German Shepherd” type, while the Ichinoseki line was referred to as the “Mastiff” type. Thus, the Ichinoseki-line rose in popularity. Goromaru-Go was regarded as the most influential akita of that line who, although didn't perform well in show, produced outstanding akita dogs when bred to Taihei and Nikkei lines from Southern Akita. Goromaru-Go then became foundation to further the Japanese type.

                 During the occupation years following the war, the breed began to thrive again through the efforts of Sawataishi and others. Morie Sawataishi and his efforts to breed the Akita is a major reason this breed exists today. For the first time, Akitas were bred for a standardized appearance. Akita fanciers in Japan began gathering and exhibiting the remaining Akitas and producing litters to restore the breed to sustainable numbers and to accentuate the ideal characteristics of the breed muddied by crosses to other breeds. It wasn't until the 1960-70's where the foxier Japanese type started to diverge from the typical American type.

                 The story of Hachikō, the most revered Akita of all time, helped push the Akita into the international dog world. Hachikō was born in 1923 and owned by Professor Hidesaburō Ueno of Tokyo. Professor Ueno lived near the Shibuya Train Station in a suburb of the city, and commuted to work every day on the train. Hachikō accompanied his master to and from the station each day. On May 25, 1925, when the dog was 18 months old, he waited for his master's arrival on the four o'clock train, but Professor Ueno had suffered a fatal brain haemorrhage at work. Hachikō continued to wait for his master's return.He travelled to and from the station each day for the next nine years. He allowed the professor's relatives to care for him, but he never gave up the vigil at the station for his master. His vigil became world-renowned when, in 1934, shortly before his death, a bronze statue was erected at the Shibuya train station in his honor. This statue was melted down for munitions during the war, but a new one was commissioned after the war. Each year on March 8 since 1936, Hachikō's devotion has been honoured with a solemn ceremony of remembrance at Tokyo's Shibuya railroad station. Eventually, Hachikō's legendary faithfulness became a national symbol of loyalty, particularly to the person and institution of the Emperor.

                 In 1967, commemorating the 50th anniversary of the founding of the Akita Dog Preservation Society, the Akita Dog Museum was built to house information, documents and photos. There is a tradition in Japan, that when a child is born they receive a statue of an Akita. This statue symbolizes health, happiness, and a long life.


                 """,
            fact: "As mentioned before, the story of Hachiko is a legendary one. The Akita would walk with his owner to the train station every day and wait on the platform for him to get home from work. One day, his owner died at the office and never returned, but Hachiko returned there every day where he continued to wait for him. When Hachiko passed away in 1935, a bronze statue was erected in his honor.", imageName:"akita",locationCoordinate: CLLocationCoordinate2D(latitude: 40.271336, longitude: 140.564646) ),
    
    Dog(title: "Golden Retriever", headline: "The Golden Retriever is a Scottish breed of retriever dog of medium size. It is characterised by a gentle and affectionate nature and a striking golden coat. It is commonly kept as a pet and is among the most frequently registered breeds in several Western European countries. It is a frequent competitor in dog shows and obedience trials; it is also used as a gundog, and may be trained for use as a guide dog.The breed was created by Sir Dudley Marjoribanks at his Scottish estate Guisachan in the late nineteenth century. He cross-bred Flat-coated Retrievers with Tweed Water Spaniels, with some further infusions of Red Setter, Labrador Retriever and Bloodhound. The breed was recognised by the Kennel Club in 1913, and during the interwar period spread to many parts of the world." , dogEra: "19th century", summary: ["1860s","Scotland","3"],
        description:"""
             The Golden Retriever was developed in Scotland in the nineteenth century by Sir Dudley Marjoribanks (later to become Baron Tweedmouth) from Flat-coated Retrievers judiciously crossed with Tweed Water Spaniels and some other British dog breeds. Prior to the 1952 publication of the very detailed stud book which had been meticulously maintained by Marjoribanks, a number of romantic tales were published about the origins of the breed.

             In the 1860s Marjoribanks set out to create what to his mind was the ultimate breed of retriever at his Scottish estate Guisachan.He started by acquiring a yellow-coloured Flat-coated Retriever dog called Nous. Nous had been whelped in June 1864 and was the only yellow pup in an otherwise all black-coloured litter. Whilst uncommon, occasionally liver, brown, golden or yellow-coloured purebred Flat-coated Retriever pups are whelped to matings of two black parents.It is the pedigree of Nous that was the source for the romantic tales of the heritage of the Golden Retriever. One early account claimed Nous was purchased from a Russian circus trainer in Brighton, another claimed he was bought from a cobbler, and yet another claimed a gypsy. The stud book states that Nous was a Flat-coated Retriever bred by Lord Chichester on his Stanmer Park estate near Brighton.

             In 1868 Nous was mated to a Tweed Water Spaniel bitch named Belle, who is recorded in the stud book as being whelped in 1863 and being of "Ladykirk breeding".The litter from this mating consisted of four yellow pups, Primrose, Ada, Cowslip and Crocus. The best bitch from this litter, Cowslip, was mated to a Tweed Water Spaniel called Tweed with the mating producing a bitch pup called Topsy. Cowslip was subsequently mated to a Red Setter called Sampson; that mating produced a dog pup called Jack. Topsy was mated with a black Flat-coated Retriever called Sambo and a bitch pup from that litter, Zoe, was mated back to Jack and two pups from that mating were retained, a dog called Nous II and a bitch called Gill. Gill was mated to a black Labrador Retriever called Tracer, and a bitch pup from that mating, Queenie, was mated back to Nous II; all Golden Retrievers descend from this mating. The progeny from these various matings varied in colour from pure black to light cream, but it was the golden-coloured ones that were retained and mated to each other, forming the foundation stock of the Golden Retriever breed. Marjoribanks is also known to have used a sandy-coloured Bloodhound and another Labrador in subsequent years of the breeding programme.

             """,
                fact: "Like other retrievers, Goldens are likely to carry something around everywhere they go, such as sticks, toys, clothing, or whatever else isn’t tied down.", imageName:"golden",locationCoordinate: CLLocationCoordinate2D(latitude: 56.8, longitude: -5) ),
    Dog(title: "Siberian Husky", headline: "TThe Siberian Husky is a medium-sized working sled dog breed. The breed belongs to the Spitz genetic family. It is recognizable by its thickly furred double coat, erect triangular ears, and distinctive markings, and is smaller than the similar-looking Alaskan Malamute.Siberian Huskies originated in Northeast Asia where they are bred by the Chukchi people of Siberia for sled pulling, and companionship. It is an active, energetic, resilient breed, whose ancestors lived in the extremely cold and harsh environment of the Siberian Arctic. William Goosak, a Russian fur trader, introduced them to Nome, Alaska, during the Nome Gold Rush, initially as sled dogs to work the mining fields and for expeditions through otherwise impassable terrain. Today, the Siberian Husky is typically kept as a house pet, though they are still frequently used as sled dogs by competitive and recreational mushers." , dogEra: "20th century", summary: ["1908","Siberian","21"],
        description:"""
             A Siberian Husky has a double coat that is thicker than that of most other dog breeds. It has two layers: a dense, finely wavy undercoat and a longer topcoat of thicker, straight guard hairs. It protects the dogs effectively against harsh Arctic winters, and also reflects heat in the summer. It is able to withstand temperatures as low as −50 to −60 °C (−58 to −76 °F). The undercoat is often absent during shedding. Their thick coats require weekly grooming. An excessively long coat, sometimes referred to as a "wooly" or "woolie" coat, is considered a fault by the breed's standard as it lacks the thicker protection of the standard coat's guard hairs, obscures the dog's clear-cut outline, causes quicker overheating during serious harness work, and becomes easily matted and encrusted with snow and ice.

             Siberian Huskies come in a variety of colors and patterns, often with white paws and legs, facial markings, and tail tip. Example coat colors are black and white, copper-red and white, grey and white, pure white, and the rare "agouti" coat, though many individuals have blondish or piebald spotting. Some other individuals also have the "saddle back" pattern, in which black-tipped guard hairs are restricted to the saddle area while the head, haunches and shoulders are either light red or white. Striking masks, spectacles, and other facial markings occur in wide variety. All coat colors from black to pure white are allowed. Merle coat patterns are not permitted by the American Kennel Club (AKC) and The Kennel Club (KC). This pattern is often associated with health issues and impure breeding.

             Eyes

             The American Kennel Club describes the Siberian Husky's eyes as "an almond shape, moderately spaced and set slightly obliquely." The AKC breed standard is that eyes may be brown, blue or black; one of each or particoloured are acceptable (complete is heterochromia). These eye-color combinations are considered acceptable by the American Kennel Club. The parti-color does not affect the vision of the dog.

             Nose
             Show-quality dogs are preferred to have neither pointed nor square noses. The nose is black in gray dogs, tan in black dogs, liver in copper-colored dogs, and may be light tan in white dogs. In some instances, Siberian Huskies can exhibit what is called "snow nose" or "winter nose." This condition is called hypopigmentation in animals. "Snow nose" is acceptable in the show ring.

             Tail
             Siberian Husky tails are heavily furred; these dogs will often curl up with their tails over their faces and noses in order to provide additional warmth. When curled up to sleep the Siberian Husky will cover its nose for warmth, often referred to as the "Siberian Swirl". The tail should be expressive, held low when the dog is relaxed, and curved upward in a "sickle" shape when excited or interested in something.

             Size
             The breed standard indicates that the males of the breed are ideally between 20 and 24 inches (51 and 61 cm) tall at the withers and weighing between 45 and 60 pounds (20 and 27 kg). Females are smaller, growing to between 19 and 23 inches (48 and 58 cm) tall at the withers and weighing between 35 and 50 pounds (16 and 23 kg). The people of Nome referred to Siberian Huskies as "Siberian Rats" due to their size of 40–50 lb (18–23 kg), versus the Alaskan Malamute's size of 75–85 lb (34–39 kg).

             Behavior
             The Husky usually howls instead of barking. They have been described as escape artists, which can include digging under, chewing through, or even jumping over fences.

             Because the Siberian Husky had been raised in a family setting by the Chukchi and not left to fend for themselves, they could be trusted with children.[26] The ASPCA classifies the breed as good with children. It also states they exhibit high energy indoors, have special exercise needs, and may be destructive "without proper care".

             Siberian Huskies have a high prey drive due to the Chukchi allowing them to roam free in the summer. The dogs hunted in packs and preyed on wild cats, birds, and squirrels, but with training can be trusted with other small animals. They would only return to the Chukchi villages when the snow returned and food became scarce. Their hunting instincts can still be found in the breed today, noted by their typically high prey-drive.[27]

             A 6 ft (1.83 m) fence is recommended for this breed as a pet, although some have been known to overcome fences as high as 8 ft (2.44 m). Electric pet fencing may not be effective. They need the frequent companionship of people and other dogs, and their need to feel as part of a pack is very strong.

             The character of the Siberian Husky is friendly and gentle. The Husky cannot be used as a guard dog; Siberian Huskies typically have no aggression towards humans. In addition, the breed often shows independence, which is a disadvantage for service dogs. Attempting to teach Siberian Huskies aggressive behavior can lead to mental problems in the dog. It can be dangerous for the owner.  The dog is intelligent, but can be stubborn because of its independence, impulsivity and inattention. To achieve obedience it is highly beneficial to start training at an early age.

             Siberian Huskies were ranked 77th out of 138 compared breeds for their intelligence by canine psychologist Stanley Coren. However, the rankings in Coren's published work utilized only one of three defined forms of dog intelligence, "Working and Obedience Intelligence", which focused on trainability—a dog's ability to follow direction and commands in a direct context, specifically by trial judges in a controlled course setting. The Siberian Husky's work as a sled dog, with minimal active direction from a driver, and a driver's reliance on the dogs to make their own decisions in poor conditions, utilizes the other two forms, "Instinctive Intelligence" and "Adaptive Intelligence", to a much greater extent.
             """,
                fact: "Huskies were developed as working sled dogs over thousands of years by the Chukchi people living in the Siberian peninsula of northeast AsiaThe area is home to one of the most hostile and extreme climates in the world—where winds can reach 100 miles per hour and temperatures can drop to 100 degrees below zero. With teams of up to 20 dogs pulling their sleds out onto the ice in their search for food, the Chukchi relied on the dogs for survival, and the dogs were central to the people’s life and culture.", imageName:"husky",locationCoordinate: CLLocationCoordinate2D(latitude: 61.01371, longitude: 99.196656) ),
    Dog(title: "Alaskan Malamute", headline: "The Alaskan Malamute (/ˈmæləˌmjuːt/) is a large breed of dog that was originally bred for its strength and endurance, to haul heavy freight as a sled dog, and as a hound.[2] It is similar to other arctic breeds such as the husky, the spitz, the Greenland Dog, Canadian Eskimo Dog, the Siberian Husky, and the Samoyed." , dogEra: "12,000 years ago", summary: ["12,000 years ago","Alaska","67"],
        description:"""
             The American Kennel Club (AKC) breed standard describes a natural range of size, with a desired size of 23 inches (58 cm) tall and 75 pounds (34 kg) for females, 25 inches (64 cm) tall and 85 pounds (39 kg) for males.[7] Heavier individuals (90 lb (41 kg)) and dogs smaller than 75 pounds (34 kg) are commonly seen. There is often a marked size difference between males and females. Weights upwards of 100 pounds (45 kg) are also seen.[7]

             The coat of the Alaskan Malamute is a double coat. The undercoat has an oily and woolly texture and can be as thick as two inches.[7] The outer guard coat is coarse and stands off the body longer at the withers but not more than one inch off the sides of the body. Ears are small in proportion to the head and stand firmly erect when at attention. The Alaskan Malamute is a heavy dog, with a more formidable nature and structure than the Siberian Husky, which is bred for speed. The Alaskan Malamute is bred for power and endurance, which is its original function and what the standard of the breed requires of Alaskan Malamute breeders.

             The usual colors are various shades of grey and white, sable and white, black and white, seal and white, red and white, or solid white.[8] There are a wide range of markings in the breed including face markings, blazes, a splash at the nape of the neck, and a collar or half collar. White is often the predominant color on the body, parts of the legs, feet, and part of the markings of the face. In terms of color variants, some Malamutes exhibit a dark grey to buff-colored undertone around their trimmings and white areas, presenting with a color-linked gene known as Agouti. Two agouti alleles, with the possibility of a third, appear to be found in Malamutes: aw (Agouti Pattern or Wolf/Wild Pattern), at (Tan Point Pattern or Black Pattern), and awat (Heterozygous Agouti or Dark Agouti).

             The eyes of the Alaskan Malamute are almond-shaped and are varied shades of brown; however, the darker eye is preferred. Purebred Alaskan Malamutes will not have blue eyes. The physical build of the Malamute is compact and strong with substance, bone and snowshoe feet.

             According to the AKC breed standard, the Malamute's tail is well furred and is carried over the back like a waving plume. Corkscrew tails are occasionally seen but are faulted in the AKC breed standard (a corkscrew tail is commonly seen in the Akita). The Malamutes well-furred tails aid in keeping them warm when they curl up in the snow. They are often seen wrapping the tail around their nose and face, which presumably helps protect them against harsh weather such as blowing snow. Their ears are generally upright, wedge-shaped, small in proportion to the head and set to the side of the skull. The muzzle is deep and broad, tapering slightly from the skull to the nose. Nose and gums are black but some Malamutes have a snow nose, which is black with a pink undertone that can get darker or lighter, depending on the season.


             """,
                fact: "They’re built to withstand cold temperatures, and were historically used in Arctic expeditions. They helped settlers hunt, track, look out for bears and also helped to haul gear across snowy terrain, pulling heavy sleds.", imageName:"alaska",locationCoordinate: CLLocationCoordinate2D(latitude: 66.160507, longitude: -153.369141) ),
    Dog(title: "Pit bul", headline: "Pit bull is a term used in the United States for a type of dog believed to have descended from bull and terriers, while in other countries such as the United Kingdom the term is used as an abbreviation of the American Pit Bull Terrier breed.[1][2][3] Within the United States the pit bull is usually considered a diverse grouping that includes the breeds American Pit Bull Terrier, American Staffordshire Terrier, American Bully, Staffordshire Bull Terrier and occasionally the American Bulldog, along with any crossbred dog that shares certain physical characteristics with these breeds. In other countries including Britain, the Staffordshire Bull Terrier is not considered a pit bull.[1][4][5] Most pit bull-type dogs descend from the British Bull and terrier, a 19th-century dog-fighting type developed from crosses between the Old English Bulldog and the Old English Terrier.[6][7][8]" , dogEra: "20th century", summary: ["20th century","British","n/a"],
        description:"""
             The term has been used since at least early 20th century.[17][3] It is believed all dogs that are now classified as pit bulls descend from the British bull and terrier, which were first imported into North America in the 1870s.[6][7] The bull-and-terrier was a breed of dog developed in the United Kingdom in the early 19th century for the blood sports of dog fighting and rat baiting, it was created by crossing the ferocious, thickly muscled Old English Bulldog with the agile, lithe, feisty Black and Tan Terrier.[6][7] The aggressive Old English Bulldog, which was bred for bear and bull baiting, was often also pitted against its own kind in organised dog fights, but it was found that lighter, faster dogs were better suited to dogfighting than the heavier Bulldog.[6][7][8] To produce a lighter, faster more agile dog that retained the courage and tenacity of the Bulldog, outcrosses from local terriers were tried, and ultimately found to be successful.[6][7][8]

             As it was in the United Kingdom, dog fighting became a popular pastime in 19th century America and bull-and-terriers were imported to the New World to pursue the blood sport.[6][7] In the United States organised dog fights have been progressively outlawed in various states since 1874, culminating in federal legislation criminalising animal fighting in 2007.[16]

             In the 1890s breeders of American pit bull-type dogs attempted to have their dogs recognised by the American Kennel Club, but because of the type's association with dogfighting, the club rejected these entreaties.[6][7] Following this rejection, in 1898 breeders of American Pit Bull Terriers established a rival kennel club, the United Kennel Club. In addition to being a breed registry, the United Kennel Club also regulated dogfights.[6][7][18] In the 1930s the American Kennel Club was faced with a dilemma, whilst not wishing to condone dogfighting there was a desire to recognise a uniquely American dog breed for which over 30 years of breed records existed.[6][7][18] The solution was to recognise Pit Bull Terriers under a different name and prohibit these dogs from being used in organised fights and in 1935 the American Kennel Club recognised Pit Bull Terriers as Staffordshire Terriers.[6][7][18]

             The name "Staffordshire Bull Terrier" was first used in Britain in 1930 in advertisements for bull-and-terrier-type dogs.[8] Organised dog fighting had been effectively eliminated in the United Kingdom by the Protection of Animals Act 1911, but devotees of the bull-and-terrier type continued to breed these dogs, predominantly in England's Black Country.[8] Throughout the early 1930s attempts were made in England to gain recognition for these dogs with The Kennel Club, these efforts were successful in 1935.[6][7][16] In order to avoid confusion with the British breed, in 1972 the American Kennel Club changed the name of their American breed to the American Staffordshire Terrier.[7][18]

             Despite criminalisation, illegal fights using pit bull-type dogs have continued to be widespread in the United States, in the 1990s in that country it was estimated 1,500 dogs died annually in organised fights and by the mid-2000s it was estimated over 40,000 people were involved in the illegal blood sport.[6][7][16] Pit bull-type dogs are also used by criminal organisations to guard illegal narcotics, and to intimidate and attack civilians, other criminals and police, the type becoming a status symbol in American gang culture.[16][19][20] On the other side of the law, pit bull-type dogs have been used by U.S. Customs and Border Protection as drug detection dogs.[21][22]

             There is a lobby of animal rights groups that are spending millions of dollars to try to rebrand pit bulls as family dogs.[23] In efforts to counter negative perceptions about pit bull-type dogs, both the San Francisco Society for the Prevention of Cruelty to Animals and the New York City Center for Animal Care and Control have unsuccessfully attempted to rename the type.[24][25]


             """,
                fact: "Aside from American Staffordshire Terriers, other pitbull breeds include the American Bully, the Staffordshire Bull Terrier, and even the American Bulldog. Crossbreeds that share the traits of these breeds also count as pitbulls among professional breeders. However, Britain doesn’t recognize the Staffordshire Bull Terrier as a pitbull.", imageName:"pitbull",locationCoordinate: CLLocationCoordinate2D(latitude: 51.509865, longitude: -0.118092) ),
    Dog(title: "Poodle,", headline: "The Poodle, called the Pudel in German and the Caniche in French, is a breed of water dog. The breed is divided into four varieties based on size, the Standard Poodle, Medium Poodle, Miniature Poodle and Toy Poodle, although the Medium Poodle is not universally recognised. They have a distinctive thick, curly coat that comes in many colors and patterns, with only solid colors recognized by breed registries. Poodles are active and intelligent, and are particularly able to learn from humans. Poodles tend to live 10–18 years, with smaller varieties tending to live longer than larger ones." , dogEra: "17th century", summary: ["17th century","Germany ","5"],
        description:"""
             Most cynologists believe the Poodle originated in Germany in the Middle Ages, from a dog similar to today's Standard Poodle. The Poodle was Germany's water dog, just as England had the English Water Spaniel, France the Barbet, Ireland the Irish Water Spaniel and the Netherlands the Wetterhoun.[1][2][3][4][5] Among the evidence used to support this theory is the Germanic name for the breed, Poodle or "Pudel" in German, which is derived from the Low German word "puddeln", meaning "to splash". Numerous works by various German artists from as early as the 17th century depict dogs of recognisably Poodle type.[1][2][3][5] Some cynologists believe the Poodle originated in France, where it is known as the "Caniche" (French for "duck dog"), and that the breed descends from the Barbet. This view is shared by the Fédération Cynologique Internationale (FCI).[6][7] Others argue that the breed originated in Russia, Piedmont or Northwest Africa.[4][7]

             Whatever the Poodle's country of origin, both their German and French breed names indicate the modern Poodle's ancestors were widely used by waterfowlers both to retrieve shot game and to recover lost arrows and bolts that had missed their mark.[3][4]

             Size variants
             Due to their intelligence, obedient nature, athleticism and looks Poodles were frequently employed in circuses, particularly in France.[2][3][5][7] In French circuses poodles were selectively bred down in size to create what is now known as the Miniature Poodle, which was known as the Toy Poodle until 1907, as a smaller sized dog is easier to handle and transport in a travelling circus.[5] As circus performers the variety was frequently seen performing all manner of tricks including walking tightropes, acting out comedies and even performing magic and card tricks.[2][3][5]

             The Toy Poodle was created at the beginning of the 20th century when breeders again bred Miniature Poodles down in size to create a popular companion dog.[2][3][5] Initially, these efforts resulted in disfigured or misshapen pups, as well as pups with behavioural problems, as a result of irresponsible breeding for dwarfed size only. As new breeding practices were adopted, the variety became set as a toy-sized replica of the original.[2][3][5] Later attempts to create an even smaller variety, the Teacup Poodle, were unable to overcome serious genetic abnormalities and were abandoned.[5]

             The last of the Poodle varieties to be recognised was the Medium Poodle, which in size is mid way in between the Standard and the Miniature Poodle. Not universally recognised by the world's kennel clubs, the Medium Poodle is recognised by the FCI and most Continental European kennel clubs.[3][5][6] One of the reasons for creating this fourth size variety may have been a desire to reduce the number of entries of Poodles by variety at conformation shows.[5]

             Recent history
             The Poodle was recognised by the Kennel Club of the United Kingdom in 1874, and by the American Kennel Club (AKC) in 1886, soon after the founding of both clubs.[8] In the United States, poodles were unpopular until 1935, when the Poodle Nunsoe Duc de la Terrace won best in show at Westminster.[9] Afterwards, they rapidly gained prominence, becoming the AKC's most registered breed from 1960 to 1982.[10] Since 1935, Poodles have won best in show at Westminster 10 times, the second-most of any breed.[11] As of 2012, the Poodle was the third-most popular FCI registered breed worldwide, after the Labrador Retriever and German Shepherd, with 118,653 new dogs registered per year from the 25 countries surveyed.[12]


             """,
                fact: "Poodles are among the smartest dog breeds. Their intelligence and eagerness to please make them great service dogs. Poodles are also employed as guide dogs, assistance dogs for people with other physical disabilities, and therapy dogs. They’ve even been utilized as truffle hunters due to their keen noses.", imageName:"poodler",locationCoordinate: CLLocationCoordinate2D(latitude: 52.520008, longitude: 13.404954) ),
    
    Dog(title: " Pug", headline: "The Pug is a breed of dog originally from China, with physically distinctive features of a wrinkly, short-muzzled face, and curled tail. The breed has a fine, glossy coat that comes in a variety of colors, most often fawn (light brown) or black, and a compact, square body with well developed and thick muscles all over the body.Pugs were brought from China to Europe in the sixteenth century and were popularized in Western Europe by the House of Orange of the Netherlands, and the House of Stuart.[2] In the United Kingdom, in the nineteenth century, Queen Victoria developed a passion for pugs which she passed on to other members of the Royal Family.Pugs are known for being sociable and gentle companion dogs.[3] The American Kennel Club describes the breed's personality as even-tempered and charming.[4] Pugs remain popular into the twenty-first century, with some famous celebrity owners, despite facing various health problems due to their bred traits.[5]" , dogEra: "16th century", summary: ["16th century","china","35"],
        description:"""
             Physical characteristics
             While the pugs that are depicted in eighteenth century prints tend to be long and lean,[2] modern breed preferences are for a square cobby body, a compact form, a deep chest, and well-developed muscle.[4] Their smooth and glossy coats can be fawn, apricot fawn, silver fawn, or black.[4][6] The markings are clearly defined and there is a trace of a black line extending from the occiput to the tail.[4] The tail normally curls tightly over the hip.[2]

             Pugs have two distinct shapes for their ears, "rose" and "button". "Rose" ears are smaller than the standard style of "button" ears, and are folded with the front edge against the side of the head. Breeding preference goes to "button" style ears.[7]

             Pugs' legs are strong, straight, of moderate length and are set well under. Their shoulders are moderately laid back. Their ankles are strong, their feet are small, their toes are well split-up, and their nails are black.[4] The lower teeth normally protrude further than their upper, resulting in an under-bite.[1]

             Temperament
             This breed is often described by the Latin phrase multum in parvo, or "much in little" or "a lot of dog in a small space", alluding to the pug's remarkable and charming personality, despite its small size.[1] Pugs are strong-willed but rarely aggressive, and are suitable for families with children. The majority of the breed is very fond of children and sturdy enough to properly play with them. Depending on their owner's mood, they can be quiet and docile but also vivacious and teasing.[8] Pugs tend to be intuitive and sensitive to the moods of their owners and are usually eager to please them.[3] Pugs are playful and thrive on human companionship. They also tend to have a snoozy nature and spend a lot of time napping. Pugs are often called "shadows" because they follow their owners around and like to stay close to the action,[9] craving attention and affection from their owners.[10][11]

             Birth and reproduction
             Pug pregnancies last an average of 63 days. The average sized litter for pugs is 4 to 6 puppies, though this can vary from 1 to 9 and still be considered normal.[12] Due to the relative size of neonatal skulls to the birth canal, pugs are highly predisposed to cesarean births.
             """,
                fact: "Because the pug lineage stretches so far back, their early history is a little murky. Most believe the breed originated in China and existed before 400 BCE and were called (or at least were closely related to a breed called) lo-sze. Buddhist monks kept the dogs as pets in Tibetan monasteries.", imageName:"pug",locationCoordinate: CLLocationCoordinate2D(latitude: 29.652491, longitude: 91.172112) ),
    Dog(title: " Welsh Corgi", headline: "TThe Welsh Corgi (/ˈkɔːrɡi/[5] or Corgi, plural Corgis, or occasionally the etymologically consistent Corgwn; /ˈkɔːrɡuːn/) is a small type of herding dog that originated in Wales. The name corgi is derived from the Welsh words cor and ci (which is mutated to gi), meaning dwarf and dog, respectively.Two separate breeds are recognized: the Pembroke Welsh Corgi and the Cardigan Welsh Corgi. Physical differences are seen between the two breeds. According to the breed standards, overall the Cardigan is larger, both in weight and height. Their tails are of different shapes, and docking was previously performed on Corgis before the practice was largely banned.Historically, the Pembroke has been attributed to the influx of dogs alongside Flemish weavers from around the 14th century, while the Cardigan is attributed to the dogs brought with Norse settlers, in particular a common ancestor of the Swedish Vallhund.The Pembroke is the more popular of the two, yet still appears on the Kennel Club's vulnerable dog breeds of the United Kingdom list.[6] The Pembroke Welsh Corgi gained in popularity because Elizabeth II had personally owned more than 30 Pembrokes or Corgi-Dachshund crosses, known as dorgis." , dogEra: "10th century", summary: [" 10th century"," South West Wales","11"],
        description:"""
             Welsh Corgis were cattle herding dogs, the type of herding dog referred to as "heelers", meaning that they would nip at the heels of the larger animals to keep them on the move.[8] The combination of their low height off the ground and the innate agility of Welsh Corgis would allow them to avoid the hooves of cattle.[8] The term "Corgi" means either cur dog or dwarf dog (cor = dwarf, gi = lenitive of ci, dog) in the Welsh language, which was not intended as an insult to the dog's size, rather as a purely descriptive term.[7][9] Different tales have been told of the Corgi's origin; some believe that the two modern breeds evolved from shared ancestry,[10] while others attribute the import of the Pembroke Welsh Corgi to Flemish weavers starting around the 10th century.[11] Further theories on the origin of the Pembroke variety suggest that they may have originated from central European herding breeds from the area around modern Germany. Depending on the time when these dogs were imported to Wales, they could have been either Deutsche Bracken or Dachshund.[9]

             The Cardigan Welsh Corgi has been attributed to the influences of Nordic settlers in the region.[12] Dogs of similar dimensions exist in modern Scandinavia, called the Swedish Vallhund,[13] and it is claimed by some historians that these two breeds share a common ancestor.[14] In the late 19th century, farmers began to switch from cattle to sheep, but the Corgi is not suited for working sheep. Similarities between the Welsh Corgis have been attributed to crossbreeding between the two, or simply selected breeding from those who wished to have the Cardigan variety appear closer in nature to the Pembroke.[14]

             The first recorded date for Corgis appearing in the show ring in Wales is 1925. Captain J. P. Howell called together a meeting of breeders of both the Pembroke and the Cardigan varieties and formed the Welsh Corgi Club, with an initial membership of 59 members. A general breed standard was drawn up, and Corgis began to appear in conformation shows. Until this point, neither breed had been specifically bred for looks. Members of this club were primarily interested in the Pembroke variety, although the Cardigan variety also appeared. At that point, the breeds were referred to as the Pembrokeshire and Cardiganshire varieties; the names were later shortened. There were a number of disputes between breeders of the two types in early shows, as judges who were breeders of one type would often favour them.[15] The Welsh Corgi appeared at Crufts—a dog show held annually in the United Kingdom—for the first time in 1927.[16]

             The first championship was awarded at a Cardiff show in 1928, to a red and white Pembroke bitch named Shan Fach. The breeds continued to be judged together until 1934, when the Kennel Club recognized each breed separately. In that initial registration, some 59 Cardigans and 240 Pembrokes were listed in the pedigree books. The decisions about the breed to which each dog belonged were sometimes left to the owners, who were free to choose whichever they felt was the most appropriate.[15] The first dog to be named best-in-show at an open conformation show was Ch. Bowhit Pivot.[17]

             Cardigan Welsh Corgis continued to be rarer than Pembrokes, with only 11 registrations made in 1940. Both breeds survived the Second World War, although the Cardigans registered with the Kennel Club numbered only 61 by the end of the war.[15] Pembrokes became very popular during the postwar years in the United Kingdom; in 1953, it was ranked as the fourth-most popular breed by the Kennel Club, behind the English Cocker Spaniel, the German Shepherd, and the Pekingese.[18] In 1955, the reserve Best in Show at Crufts was the Pembroke Welsh Corgi Kaytop Maracas Mint.[19] The Corgi breeds declined in popularity: veterinary physician Brian Singleton suggested in The Times in 1963 that this was due to issues with their temperament.[20] The Cardigan Welsh Corgi was listed in the Kennel Club's first list of Vulnerable Native Breeds in 2006.[21] This list is for those breeds which register less than 300 dogs in any one year;[22] there had been 84 Cardigan Corgis registered in 2006. After an initial increase, this declined to 46 in 2010, but then rose to the highest numbers since the list began in 2015, with a total of 124 puppies registered.[21] In 2013, the Pembroke Welsh Corgi was also added, as there had been only 241 puppies registered that year. While the Kennel Club blamed this on the importation of foreign dog breeds,[22] The Daily Telegraph blamed the decline on the ban on tail docking introduced six years before.[23] However, 2015 had an increase of 34% in the number of Pembroke registrations; the popularity of Corgis on Instagram was credited for the change. Pembrokes were removed from the Vulnerable Native Breeds list in 2016.[24][25]
             """,
                fact: "Welsh legend says the fairies and elves of Wales used the Pembroke Welsh Corgi to pull fairy coaches, work fairy cattle, and serve as the steed for fairy warriors. If you look closely, even today you can see the marks of the “fairy saddle” over the shoulders in the Pembroke’s coat.", imageName:"cogi",locationCoordinate: CLLocationCoordinate2D(latitude: 51.209000, longitude: -2.647000) ),
    
    Dog(title: " Phu Quoc Ridgeback", headline: "The Phu Quoc Ridgeback (Vietnamese: Chó Phú Quốc) is a rare breed of dog from the island of Phú Quốc in Kiên Giang Province in southern Vietnam. It is one of three ridgeback breeds, the others being the Rhodesian Ridgeback and the Thai Ridgeback. It is not recognized by the Fédération Cynologique Internationale or any other major club. The Phu Quoc Ridgeback is one of the four native Vietnamese dog breeds, along with the Bắc Hà dog (Chó Bắc Hà), Lài dog (chó lài), Hmong Bobtail Dog (chó H’Mông cộc đuôi)." , dogEra: "19th century", summary: ["19th century","Vietnam","n/a"],
        description:"""
             There is considerable debate as to exactly when and how the breed arrived to the island of Phú Quốc. The breed was originally a landrace developed as a semi-feral companion to hunt for food and guard the homes of native islanders.[6] French colonists recognized the distinct dogs as a unique breed in the 19th century, and two resided at the Jardin d’Acclimitation in Paris.[7][8] Historically, Phu Quoc Ridgebacks were not purposefully bred, instead relying on random pairings in the relative isolation of island life to continue to maintain their unique population. According to native Phú Quốc islanders, there were originally three sizes of the breed, each uniquely bred to hunt different sizes of game over different terrains.[9] Unfortunately, purebred examples became scarce after the introduction of non-native dogs to the island, with many French writers noting that the breed was near extinction by the turn of the 20th century. [8][10]

             Despite the near extinction, genetic studies indicate that the Phu Quoc Ridgeback population is genetically diverse.[11] It was commonly thought that the Phu Quoc Ridgeback derives from the Thai Ridgeback, but recent research suggests otherwise.[12] According to a genetic analysis, the Phu Quoc Ridgeback is most closely related to Korea's Pungsan dog.[13] The breed population has been resurging as public interest grows. A Phu Quoc Ridgeback won the Hanoi dog show in 2013.[14][15] The breed was selected as the mascot for the 2018 annual Nguyen Hue Flower Street in Ho Chi Minh City, symbolizing the lunar Year of the Dog as per the Vietnamese zodiac.
""",
                fact: "They were bred in three different sizes to hunt various types of game.", imageName:"phuquoc",locationCoordinate: CLLocationCoordinate2D(latitude: 10.116848, longitude: 103.981256) )
    


    
    ]
